webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.model import db

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(100))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50))
    
    def set_password(self, password):
        self.password = generate_password_hash(password)
        
    def check_password(self, password):
        return check_password_hash(self.password, password)
    
    @property
    def is_admin(self):
        return self.role == 'admin'
    
    def __repr__(self):
        return '<User {}>'.format(self.username)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webapp.user.models import User

class Loginform(FlaskForm):
    username = StringField('Username', validators=[DataRequired()], render_kw={'class': 'form-control'})
    password = PasswordField('Password', validators=[DataRequired()], render_kw={'class': 'form-control'})
    submit = SubmitField('Submit', render_kw={'class': 'btn btn-primary'})
    remember_me = BooleanField('Remember me', default=True, render_kw={'class': 'form-check-input'})
    
class Registrationform(FlaskForm):
    username = StringField('Username', validators=[DataRequired()], render_kw={'class': 'form-control'})
    email = StringField('Email', validators=[DataRequired(), Email()], render_kw={'class': 'form-control'})
    password = PasswordField('Password', validators=[DataRequired()], render_kw={'class': 'form-control'})
    password2 = PasswordField('Write your password again', validators=[DataRequired(), EqualTo('password')], render_kw={'class': 'form-control'})
    submit = SubmitField('Submit', render_kw={'class': 'btn btn-primary'})
    
    def validate_username(self, username):
        user_count = User.query.filter_by(username=username.data).count()
        if user_count > 0:
            raise ValidationError('Пользователь с таким именем уже существует')
        
    def validate_email(self, email):
        user_count = User.query.filter_by(email=email.data).count()
        if user_count > 0:
            raise ValidationError('Пользователь с такой эл. почтой уже существует')
        

webapp/user/views.py
from flask import Blueprint ,render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, current_user, login_required

from webapp import db
from webapp.user.forms import Loginform, Registrationform
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    title = "Авторизация"
    login_form = Loginform()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = Loginform()
    
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("You are into my website, nice!")
            return redirect(url_for('index'))
        
    flash("Username or Password are not correct, sorry")
    return redirect(url_for('user.login'))

    
@blueprint.route('/logout')
def logout():
    logout_user()
    flash("See you later, space cowboy")
    return redirect(url_for('index'))

@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = Registrationform()
    title = "Регистрация"
    return render_template('user/registarion.html', page_title=title, form=form)
    
@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = Registrationform()
    
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.register'))

webapp/templates/user/login.html
{% extends 'base.html' %}

{% block content%}
    <div class = 'row'>
        <div class = 'col-4'>
            <form action="{{  url_for('user.process_login') }}" method="post">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}<br>
                    {{ form.password() }}
                </div>
                <div class='form-group form-check'>
                    {{ form.remember_me() }}
                    {{ form.remember_me.label(class_ ='form-check-label') }}
                </div>
                {{ form.submit() }}
            </form>
        </div>
        <div class = 'col-8'>
        </div>
    </div>
{% endblock%}

webapp/templates/user/registarion.html
{% extends 'base.html' %}
{% block content%}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class = 'row'>
        <div class = 'col-4'>
            <form action="{{  url_for('user.process_reg') }}" method="post">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.email.label }}
                    {{ form.email() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}<br>
                    {{ form.password() }}
                </div>
                <div class="form-group">
                    {{ form.password2.label }}<br>
                    {{ form.password2() }}
                </div>
                    {{ form.submit() }}
            </form>
        </div>
        <div class = 'col-8'>
        </div>
    </div>
{% endblock%}