webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')

@blueprint.route('/')
@admin_required
def admin_index():
    title = 'Admin panel'
    return render_template('admin/index.html', page_title=title)          

webapp/user/views.py
from flask import Blueprint ,render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, current_user, login_required

from webapp import db
from webapp.user.forms import Loginform, Registrationform
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    title = "Авторизация"
    login_form = Loginform()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = Loginform()
    
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("You are into my website, nice!")
            return redirect(url_for('index'))
        
    flash("Username or Password are not correct, sorry")
    return redirect(url_for('user.login'))

    
@blueprint.route('/logout')
def logout():
    logout_user()
    flash("See you later, space cowboy")
    return redirect(url_for('index'))

@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = Registrationform()
    title = "Регистрация"
    return render_template('user/registarion.html', page_title=title, form=form)
    
@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = Registrationform()
    
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.register'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet"
    href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <link rel='stylesheet' href='{{ url_for("static", filename="style.css") }}'>
    <title>{{ page_title }}</title>
  </head>
  <body>
    {% include 'menu.html' %}
    <div class = 'container'>
    <h1>{{ page_title }}</h1>
    {% block content %}{% endblock  %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/index.html
{% extends 'base.html' %}

{% block content%}
<div class='container'>
    <h1>{{text}}</h1>
    <ol>
        <li>Сделать Регистрацию пользователей</li>
        <li>Сделать Todo ао гайду</li>
        <li>Объединить базу данных, пользователя и его задания</li>        
    </ol>
</div>
{% endblock %}

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Трекер эффективности</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Главная Страница</a>
      </li>
      {% if current_user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main_app.index')}}">Мои задачи</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
    </form>
    <ul class="navbar-nav">
      {% if current_user.is_authenticated %}
          <li class="nav-item">
              <span class="nav-link">Привет, {{ current_user.username}}</span>
          </li>
          {% if current_user.is_admin %}
              <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('admin.admin_index')}}">Админка</a>
              </li>
          {% endif %}
          <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('user.logout')}}">Выйти</a>
          </li>
      {% else %}
          <li>
              <a class="nav-link" href="{{ url_for('user.register')}}">Регистрация</a>
          </li>
          <li>
              <a class="nav-link" href="{{ url_for('user.login')}}">Войти</a>
          </li>
      {% endif %}
      </li>
    </ul>
  </div>
</nav>