webapp/main_app/models.py
from sqlalchemy.orm import relationship
from datetime import datetime

from webapp.model import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    Done = db.Column(db.Boolean)
    created = db.Column(db.DateTime, nullable=False, default=datetime.now())
    
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True
    )
    
    user = relationship('User', backref='todo')
    
    def __repr__(self):
        return '<Id {}>'.format(self.id)

webapp/main_app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField
from wtforms.validators import DataRequired

class TodoForm(FlaskForm):
    task = StringField('Ваша задача', validators=[DataRequired()], render_kw={"class":"form-control"})
    add_button = SubmitField('Добавить',  render_kw={"class":"btn btn-primary"})
    success_button = SubmitField('Сделано', render_kw={"class":"btn btn-success"})

webapp/main_app/views.py
from flask import Blueprint, render_template, flash, redirect, request, url_for
from flask_login import current_user

from webapp import db
from webapp.main_app.forms import TodoForm
from webapp.main_app.models import Todo

blurptint = Blueprint('main_app', __name__, url_prefix='/main_app')


@blurptint.route('/')
def index():
    todo_form = TodoForm()
    incomplete = Todo.query.filter_by(Done=False, user_id =current_user.id).all()
    complete = Todo.query.filter_by(Done=True, user_id =current_user.id).all()
    return render_template('main_app/index.html', incomplete=incomplete, complete=complete, form=todo_form)


@blurptint.route('/add', methods=['POST'])
def add():
    todo_form = TodoForm()
    todo = Todo(text=request.form['task'], user_id =current_user.id, Done=False)
    db.session.add(todo)
    db.session.commit()
    
    return redirect(url_for('main_app.index', form=todo_form))

@blurptint.route('/update', methods=['POST'])
def update():
    todo_form = TodoForm()
    ids = []
    print(request.form)
    dict_of_ids = request.form
    for id in dict_of_ids:
        try:
            ids.append(int(id))
        except ValueError:
            pass

    for number in ids:
        todo = Todo.query.filter_by(id=number).first()
        todo.Done = True
        db.session.commit()
            
    return(redirect(url_for('main_app.index', form=todo_form)))

webapp/templates/main_app/index.html
{% extends 'base.html' %}
{% block content%}
    <h1>Todo List</h1>
    <div>Add a new todo item: 
        <form action="{{  url_for('main_app.add') }}" method="POST">
            {{ form.hidden_tag()}}
            <div class="form-group">
                {{ form.task.label }}
                {{ form.task()}}
            </div>
            {{ form.add_button() }}
        </form>
    </div>
    <div>
        <h2>Incomplete Items</h2>
        <form action="{{  url_for('main_app.update') }}" method="POST">
            <ul>
                {% for todo in incomplete %}
                <li style='front-size: 30pt'><input name=' {{ todo.id }}' type='checkbox'> {{todo.text}}</li>
                {% endfor %}    
            </ul>
            {{ form.success_button() }}
        </form>
        <h2>Completed Items</h2>
        <ul>
            {% for todo in complete %}
            <li style="font-size: 15pt">{{ todo.text }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock%}